version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run:
          name: run tests
          command: |
            export COVERALLS_REPO_TOKEN=F4AALtuO8fA62vsdfuhkm3Tw46RDzOmZD >> $BASH_ENV
            npm test -- -u
            npm run coverage
            
      - store_artifacts:
          path: coverage
          destination: coverage